spring:
  application:
    name: pos-carts-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/aw09
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
#  jpa:
#    show-sql: true
#  batch:
#    jdbc:
#      initialize-schema: always

server:
  port: 8000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
  instance:
    instance-id: ${spring.application.name}:${random.uuid}
management:
  health:
    rabbit:
      enabled: false
