spring:
  application:
    name: pos-order-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/aw08
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true

server:
  port: 9000
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/
management:
  health:
    rabbit:
      enabled: false
logging:
  level:
    root: INFO
