spring:
  application:
    name: pos-delivery-service
  datasource:
    url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/aw08
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
#      binders:
#        local_rabbit:
#          type: rabbit
#          environment:
#            spring:
#              rabbitmq:
#                host: localhost
#                port: 5672
#                username: guest
#                password: guest
server:
  port: 10000
management:
  health:
    rabbit:
      enabled: false
logging:
  level:
    root: INFO
